services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - wp_files:/var/www/wordpress
    networks:
        - inception_net
   
  wordpress:
    build: ./requirements/wordpress/
    container_name: wp_php
    restart: always
    depends_on:
      - mariadb
    environment:
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_EMAIL: ${WP_EMAIL}
      WP_PASSWORD: ${WP_PASSWORD}
      WP_DATABASE: ${WP_DATABASE}
      WP_URL: ${WP_URL}
      WP_REDIS_HOST: ${WP_REDIS_HOST}
      WP_REDIS_PORT: ${WP_REDIS_PORT}
      WP_REDIS_SCHEME: ${WP_REDIS_SCHEME}
      FTP_USER: ${FTP_USER}
      FTP_PASSWORD: ${FTP_PASSWORD}
    volumes:
      - wp_files:/var/www/wordpress
    expose:
      - "9000"
    networks:
      - inception_net
    
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception_net

  redis:
    build: ./requirements/bonus/redis/
    container_name: redis
    restart: always
    depends_on:
      - wordpress
    ports:
      - 6379:6379
    networks:
      - inception_net

  ftp:
    build: ./requirements/bonus/ftp/
    container_name: ftp
    restart: on-failure
    ports:
      - "21:21"
      - "40000-40005:40000-40005"
    volumes:
     - wp_files:/home/${FTP_USER}/ftp
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASSWORD: ${FTP_PASSWORD}
    networks:
      - inception_net
    
  static_web:
    build: ./requirements/bonus/static_web/
    container_name: static_web
    restart: always
    ports:
      - "8081:81" 
    networks:
      - inception_net

  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: on-failure
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
      - inception_net
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
      - ADMINER_DEFAULT_USERNAME=${MYSQL_USER}
      - ADMINER_DEFAULT_PASSWORD=${MYSQL_PASSWORD}


networks:
  inception_net:
    driver: bridge

volumes:
  mariadb:
    name: "mariadb"
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /home/jaimesan/data/mariadb
  wp_files:
    name: "wp_files"
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /home/jaimesan/data/wp_files