services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - wp_files:/var/www/wordpress
    networks:
        - inception_net
   
  wordpress:
    build: ./requirements/wordpress/
    container_name: wp_php
    restart: always
    depends_on:
      - mariadb
    environment:
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_EMAIL: ${WP_EMAIL}
      WP_PASSWORD: ${WP_PASSWORD}
      WP_DATABASE: ${WP_DATABASE}
      WP_URL: ${WP_URL}
    volumes:
      - wp_files:/var/www/wordpress
    expose:
      - "9000"
    networks:
      - inception_net
    
  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception_net


networks:
  inception_net:
    driver: bridge

volumes:
  mariadb:
    name: "mariadb"
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /home/jaimesan/data/mariadb
  wp_files:
    name: "wp_files"
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /home/jaimesan/data/wp_files