CREATE DATABASE IF NOT EXISTS wordpress_db;
CREATE USER IF NOT EXISTS 'myuser'@'%' IDENTIFIED BY 'mypassword';
GRANT ALL PRIVILEGES ON wordpress_db.* TO 'myuser'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
